#define CONFIG_ESP8266_TRANSMITTER
//#define CONFIG_SYMAX_X5C
//#define CONFIG_V2X2


#ifdef CONFIG_SYMAX_X5C
#define SUB_PROTOCOL_TYPE SUB_PROTOCOL_TYPE_SYMAX
//#define SUB_PROTOCOL_TYPE SUB_PROTOCOL_TYPE_SYMAX5C
//#define JOYSTICK_BUTTON
#define DEBUG_NK
#define DEBUG_PORT_HWSERIAL
#endif

#ifdef CONFIG_V2X2
#define SUB_PROTOCOL_TYPE SUB_PROTOCOL_TYPE_V2X2
//#define SUB_PROTOCOL_TYPE SUB_PROTOCOL_TYPE_JXD506
//#define DEBUG_NK
#define DEBUG_PORT_HWSERIAL
#endif

#ifdef CONFIG_ESP8266_TRANSMITTER
#define SKYCOPTER
#define JOYSTICK_BUTTON
#define ADS1115
#define DEBUG_NK
#define DEBUG_PORT_HWSERIAL
//#define DEBUG_PORT_SWSERIAL
#endif
